"""empty message

Revision ID: 587bdce6c354
Revises: aadbb2c55458
Create Date: 2021-06-15 10:25:09.765917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587bdce6c354'
down_revision = 'aadbb2c55458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_result_title', table_name='result')
    op.create_index(op.f('ix_result_title'), 'result', ['title'], unique=False)
    op.drop_index('ix_result_year', table_name='result')
    op.create_index(op.f('ix_result_year'), 'result', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_year'), table_name='result')
    op.create_index('ix_result_year', 'result', ['year'], unique=False)
    op.drop_index(op.f('ix_result_title'), table_name='result')
    op.create_index('ix_result_title', 'result', ['title'], unique=False)
    # ### end Alembic commands ###
