"""empty message

Revision ID: aadbb2c55458
Revises: 
Create Date: 2021-06-14 11:43:58.998868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadbb2c55458'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('imdbID', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('imdbID')
    )
    op.create_index(op.f('ix_result_title'), 'result', ['title'], unique=True)
    op.create_index(op.f('ix_result_year'), 'result', ['year'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_year'), table_name='result')
    op.drop_index(op.f('ix_result_title'), table_name='result')
    op.drop_table('result')
    # ### end Alembic commands ###
